[project]
name = "homeworks-oop-vitaliy-gubin"
version = "0.1.0"
description = ""
authors = [
    {name = "VitaliyGubin",email = "trofim-83@mail.ru"}
]
readme = "README.md"

[tool.poetry.dependencies]
black = "26.3.1"
flake8 = ">=7.3.0"
isort = ">=7.0.0"
mypy = ">=1.18.2"
openpyxl = "^3.1.5"
pandas = "^3.0.2"
pandas-stubs = "==3.0.0.260204"
platformdirs = "^4.5.1"
poetry-core = "^2.2.1"
pytest = ">=9.0.2"
pytest-cov = ">=7.0.0"
python = "^3.14"
python-dotenv = "^1.2.2"
requests = "^2.13.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=25.9.0,<27.0.0)",
    "isort (>=7.0.0,<8.0.0)",
    "mypy (>=1.18.2,<2.0.0)"
]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]

[tool.black]
line-length = 119
exclude = '''
(
  /(
    \.git
    )/
)
'''

[tool.isort]
line_length = 119

[tool.mypy]
disallow_untyped_defs = true
warn_return_any = true
exclude = '.venv'
mypy_path = "src"
